title: <p align="center"> Rahul Kunjumon </p>
logo: /assets/img/RAHULPassportpic.png

description:
  <p align="center">
  <a href="docs/RahulResume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rahulkunjumon/">LinkedIn</a> |
  
  <br>   
  SENIOR QA ENGINEER II in Performance and Automation at Rakuten India Pvt. Ltd. at Rakuten India
  <br>
  </p>
google_analytics:
theme: jekyll-theme-minimal
